Model Creation, RSPEC for validations and associations
santosral/rails-base-project pull request #1
Opened 2021-07-13 09:27 UTC by desoto13

Created RSPEC for validations and associations on the following:
- admin_spec
- article_spec
- comment_spec
- food_group_spec
- food_spec
- nutritional_information_spec
- nutritionist_spec
- user_spec

Created devise Models
-User
-Nutritionist
-Admin
note: added Parameter Sanitizer as these 3 models are separated (not using STI)

Created our Models DB with associations
-Article
-Comment
-Food Group
-Food
-Nutritional Information

2021-07-13 12:14 UTC, analyn-cajocson requested changes
why did you rename the `config/credentials.yml.enc` to `config/credentials.yml`?

2021-07-13 12:14 UTC, analyn-cajocson commented on app/models/nutritionist.rb
> +  # end
remove unnecessary comments

2021-07-14 01:52 UTC, desoto13 commented on app/models/nutritionist.rb
> +  # end
Done on revisions

2021-07-14 11:31 UTC, analyn-cajocson approved these changes

2021-07-14 11:33 UTC, merged